### ISSUE TITLE
Old Registry Address

### ISSUE THREAD

**Issue by yankev** [curvefi/curve-subgraph#2]
Hi, I noticed that the latest registry address has changed to: 0x90E00ACe148ca3b23Ac1bC8C240C2a7Dd9c2d7f5.
If we're looking to handle all `pool_added` events from both the old and current contract, would we need to add this data source as well?
Thanks.

**Comment by pioul** [comment]
👍 You're totally right, I'll make sure to add it soon!

Note to self: add the new registry dynamically as a new data source with dataSource.create(), else fall back to adding it as a static data source since it's not changing often at all

**Comment by pioul** [comment]
Fixed in 490fbbc8ad77d1d932522d2a00a8667a03aa859e
